// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsfkczszyobcuxsfatsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZmtjenN6eW9iY3V4c2ZhdHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjIyNjUsImV4cCI6MjA1NTc5ODI2NX0.VyOwTeJhECn3cCJ4EXusMeLPxICrnaZPtGM9a96yCy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);